######################################################################
# Automatically generated by qmake (3.1) Mon Jul 15 02:08:40 2019
######################################################################

TEMPLATE = app
TARGET = ./test
INCLUDEPATH += ../interfaces
DEFINES += QT_DEPRECATED_WARNINGS
LIBS += -lgcov
QT += core
QMAKE_CXXFLAGS += -fprofile-arcs -ftest-coverage

SOURCES += main.cpp
