version: 1.0
jobs:
  build:
    docker:
      - image: ubuntu:19.04

    environment:
      BASE_DIR: ~/
    
    working_directory: $BASE_DIR

    steps:
      - run:
          command: apt-get install git
      - checkout

      - run:
          command: git clone git@github.com:opensalad/interfaces.git ../
      - run:
          command:  make
          
