name: "Build, test and release"
on:
  push:
    branches: master
jobs:
  build_test_release:
    name: "Test code coverage"
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello world"