name: "Make a library"
on:
  push:
    branches: master
jobs:
  my_first_job:
    name: "First Job"
    runs-on: ubuntu-latest
    steps:
    - name: "Greeting 1"
      run: echo Hello from first step.
  parallel_job:
    name: "Parallel job"
    runs-on: ubuntu-latest
    steps:
    - name: "Greeting 2"
      run: echo Hello from parallel step.
  dependent_job:
    name: "dependent job"
    needs: my_first_job
    runs-on: ubuntu-latest
    steps:
    - name: "Greeting 3"
      run: echo Hello from 3 step.
